### ISSUE TITLE
Add support for Driver###, PlatformRecovery#### and SysPrep####

### ISSUE THREAD

**Issue by leiflindholm** [rhinstaller/efibootmgr#40]
The Driver*, PlatformRecovery* and SysPrep* variables function very much like the Boot* ones.

It would be really neat if efibootmgr was extended to permit updating these related functionalities as well.

**Comment by vathpela** [comment]
There is some chance 9a06afc will even work for --sysprep and --driver. Give it a try?  I can't do --sysprep locally (firmware rejects it) but --driver works for me.

PlatformRecovery#### is, of course, something we shouldn't be setting.  OsRecovery#### and OsRecoveryOrder will have to be a different issue than this, since it's got crypto complications.

**Comment by vathpela** [comment]
This code is in efibootmgr-13.  Maybe it even works!
